server:
  address: ":8085"
  cors:
    enabled: true
    allowOrigins:
      - "https://floatdream.cn"
      - "http://localhost:8080"

database:
  web:
    source: "mysql"
    dsn: "floatdream:floatdream@tcp(localhost:3306)/floatdream_web?charset=utf8mb4&parseTime=True&loc=Local"
  authMe:
    source: "mysql"
    dsn: "floatdream:floatdream@tcp(localhost:3306)/floatdream_authme?charset=utf8mb4&parseTime=True&loc=Local"
  game:
    source: "mysql"
    dsn: "floatdream:floatdream@tcp(localhost:3306)/floatdream_game?charset=utf8mb4&parseTime=True&loc=Local"

recaptcha:
  secret: "6Lceo6wUAAAAABzhgqA4vuRcyGhntTmNk0Z29Fl-"

game:
  address: "10.6.6.66:3306"

xorpay:
  appId: "4415"
  appSecret: "690f671eb0424a5aa152962545b6b69b"
  notifyUrl: "https://endxegen9c9kn.x.pipedream.net"
#  notifyUrl: "https://floatdream.cn/api/topup/callback"